___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [ ]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [2]:
import numpy 
print(numpy.__version__)
print(numpy.show_config())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/lidao/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/lidao/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/lidao/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/lidao/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/lidao/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/lidao/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/lidao/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/lidao/anaconda3\\Library\\include']
None


Створити вектор з 10 елементів, заповнений одиницями:

In [5]:
import numpy as np
Z = np.ones((1, 10))
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Створити вектор із значеннями від 0 до 10:

In [8]:
import numpy as np
Z = np.arange(0, 11, 1)
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10]


Створити матрицю 5 на 5, заповнену нулями:

In [10]:
import numpy as np
Z = np.zeros((5, 5))
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [54]:
import numpy as np
Z = np.random.randint(0, 20, (1, 20))

print(Z)
Y = np.where((Z!=0))
print("Ненульомі елементи мають індекси розміщені у другому array:", Y )

[[ 1  5  8  9 13  9 16 11  5 10 14 19 13  8  0 13  7 12  6  0]]
Ненульомі елементи мають індекси розмыщены у другому array: (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 15, 16, 17,
       18], dtype=int64))


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [57]:
import numpy as np
Z = np.random.randint(0, 20, (1, 20))
Mn = np.mean(Z)
Md = np.median(Z)
Std = np.std(Z)
print('Середнє значення:', Mn)
print('Медіана:', Md)
print('Стандартне відхилення:', Std)

Середнє значення: 10.9
Медіана: 11.5
Стандартне відхилення: 5.356304696336832


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [156]:
import numpy as np
Z = np.random.random((4, 2))
Y = np.random.random((2, 2))
Q = np.dot(Z, Y)
print(Q)


[[0.53848762 0.72721244]
 [0.23215561 0.3049787 ]
 [0.65783321 0.94548604]
 [0.53735944 0.64760702]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [157]:
A = np.reshape(Q, -1)
print(A)
Max =np.max(A)
Min = np.min(A)
inx = np.where((A == np.max(A)))
A[inx] = 0
print('Максимальне значення:', Max, 'Мінімальне значення:', Min)
print('Матриця з заміненим максимальним значенням:',A)

[0.53848762 0.72721244 0.23215561 0.3049787  0.65783321 0.94548604
 0.53735944 0.64760702]
Максимальне значення: 0.9454860390265115 Мінімальне значення: 0.23215560701034063
Матриця з заміненим максимальним значенням: [0.53848762 0.72721244 0.23215561 0.3049787  0.65783321 0.
 0.53735944 0.64760702]


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [127]:
B, C, D, E = np.vsplit(Q, 4)


In [128]:
K = np.corrcoef(B, C)
L = np.corrcoef(B, D)
M = np.corrcoef(B, E)
print('Кореляція першого і другого рядка', K)
print('Кореляція першого і третього рядка', L)
print('Кореляція першого і четвертого рядка', M)

Кореляція першого і другого рядка [[ 1. -1.]
 [-1.  1.]]
Кореляція першого і третього рядка [[1. 1.]
 [1. 1.]]
Кореляція першого і четвертого рядка [[1. 1.]
 [1. 1.]]


Дано матрицю. Знайти ранг матриці:

In [133]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

np.linalg.matrix_rank(a)

3

Знайти визначник матриці:

In [134]:
np.linalg.det(a) 

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [135]:
np.linalg.eigh(a) 

(array([-14.30540864,  -4.34740072,  23.65280936]),
 array([[ 0.15315575,  0.88160309,  0.44645191],
        [ 0.63674998, -0.43353159,  0.6376518 ],
        [-0.75570681, -0.18661821,  0.62775861]]))

Знайдіть число, що найчастіше зустрічається в масиві:

In [158]:
a = np.random.randint(0,10,50)
print('Число, котре найчастіше зустрічається в масиві',np.bincount(a).argmax())

Число, котре найчастіше зустрічається в масиві 8


Виведіть лише парні числа, що діляться на 5:

In [159]:
a = np.random.randint(0,10,50)
a = a[a%2==0]
a = a[a%5==0]
print('Парні числа, що діляться на 5', a)

Парні числа, що діляться на 5 [0 0 0 0]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [148]:
import numpy as np
M1 = numpy.array([[2., 5.], [1., -10.]]) 
v1 = numpy.array([1., 3.])
numpy.linalg.solve(M1, v1)

array([ 1. , -0.2])